
import type { LucideProps } from "lucide-react";
import {
  Bot,
  BrainCircuit,
  Cloud,
  Cloudy,
  Droplets,
  HeartPulse,
  LayoutDashboard,
  Leaf,
  Newspaper,
  Sun,
  Thermometer,
  Wind,
  Bug,
  TrendingUp,
  Landmark,
  Eye,
  Gauge,
  Sunrise,
  Sunset,
  ScanLine,
  Map,
  Calculator,
  Store,
  Bell,
  User,
  BookOpen,
  Shield,
} from "lucide-react";

export const Icons = {
  Logo: (props: LucideProps) => (
    <Leaf {...props} />
  ),
  Dashboard: LayoutDashboard,
  Irrigation: Droplets,
  PlantHealth: HeartPulse,
  CropRecommendation: BrainCircuit,
  News: Newspaper,
  Weather: Thermometer,
  Sun,
  Cloud,
  Wind,
  Leaf,
  Assistant: Bot,
  Pest: Bug,
  MarketInsights: TrendingUp,
  GovernmentSchemes: Landmark,
  CropInsurance: Shield,
  Thermometer: Thermometer,
  Pressure: Gauge,
  Visibility: Eye,
  AlertIcon: Cloudy,
  UV: (props: LucideProps) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/></svg>
  ),
  Sunrise,
  Sunset,
  SeedScanner: ScanLine,
  FarmMap: Map,
  Calculator,
  YieldPrediction: TrendingUp,
  FertilizerShops: Store,
  Notification: Bell,
  User,
  CultivationTips: BookOpen,
};
